volumes:
  data-db:

services:
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - "5432:5432"
#    expose:
#      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - data-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cmm-net

  backend:
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
#    expose:
#      - 8000
    environment:
      PRODUCTION_MODE: "${PRODUCTION_MODE}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./staticfiles:/var/app/staticfiles
    build:
      context: CashMovementManagement
    command: bash -c "
      python manage.py migrate
      && python manage.py create_example_data
      && python manage.py collectstatic --noinput --clear
      && gunicorn CashMovementManagement.wsgi -b 0.0.0.0:8000
      "
#      && gunicorn CashMovementManagement.wsgi -b 0.0.0.0:8000
#      && python manage.py runserver 0.0.0.0:8000
#      && python manage.py create_example_data
    develop:
      watch:
        - action: sync+restart
          path: ./CashMovementManagement
          target: ./var/app
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile
    networks:
        - cmm-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/var/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - cmm-net

#  nginx:
#    build:
#      context: ./nginx
#    ports:
#      - '8000:80'
#    depends_on:
#      - backend
#    networks:
#      - cmm-net

networks:
    cmm-net:
        driver: bridge