# Generated by Django 5.2 on 2025-04-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Transactions.type'),
            preserve_default=False,
        ),
    ]
