# Generated by Django 5.2 on 2025-04-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_category_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent_category', 'type')},
        ),
    ]
